#!/bin/bash
sudo mv /etc/pacman.conf /etc/pacman.conf.back
sudo cp arch_kdex/pacman.conf /etc/pacman.conf
sudo pacman -S haveged
sudo systemctl enable haveged
sudo systemctl start haveged
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -Syy
sudo pacman -S xfce4 kdebase-workspace appmenu-qt4 gvfs lightdm lightdm-gtk-greeter gtk-engines xorg-xprop appmenu-qt pulseaudio pulseaudio-alsa pavucontrol thunar-archive-plugin xfce4-notifyd ristretto p7zip zip unzip unrar xfce4-clipman-plugin speedtest-cli mlocate gstreamer0.10-good-plugins networkmanager network-manager-applet kde-wallpapers xfce4-whiskermenu-plugin youtube-dl xdg-user-dirs-gtk
xdg-user-dirs-update
sudo updatedb
sudo systemctl enable lightdm
sudo systemctl enable NetworkManager
sudo systemctl enable accounts-daemon
sudo mkdir /root/.gnupg
rm -r ~/.config
rm -r ~/.local
rm -r ~/.kde4
rm -r ~/.cache/*
cp -r arch_kdex/.config ~/.config
cp -r arch_kdex/.local ~/.local
cp -r arch_kdex/.kde4 ~/.kde4
mv ~/.bashrc ~/.bashrc.back
cp -r arch_kdex/.bashrc ~/.bashrc
chmod +x cp -r arch_kdex/aur_ins
arch_kdex/aur_ins
